### ISSUE TITLE
UnicodeDecodeError: 

### ISSUE THREAD

**Issue by IvanMalison** [pylast/pylast#114]
``` python
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-15-db14bc4b864f> in <module>()
----> 1 t.network.get_play_links('track', tracks)

/usr/local/lib/python2.7/site-packages/pylast.pyc in get_play_links(self, type, things, cacheable)
    770                 params['track[' + str(i) + ']'] = thing.title
    771
--> 772         doc = _Request(self, method, params).execute(cacheable)
    773
    774         seq = []

/usr/local/lib/python2.7/site-packages/pylast.pyc in __init__(self, network, method_name, params)
   1006
   1007         for key in params:
-> 1008             self.params[key] = _unicode(params[key])
   1009
   1010         (self.api_key, self.api_secret, self.session_key) = \

/usr/local/lib/python2.7/site-packages/pylast.pyc in _unicode(text)
   3937             return text
   3938         else:
-> 3939             return unicode(text)
   3940
   3941

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)
```

Do you know about the six library? I think a lot of these unicode errors + all the complicated custom logic for handling strings could be avoided if that were used.

**Comment by hugovk** [comment]
Yes, know of six and I'm all for making Unicode handling simpler.

[Six says](https://pypi.python.org/pypi/six):

> It is contained in only one Python file, so it can be easily copied into your project. (The copyright and license notice must be retained.)

Pylast has always had no extra dependencies but Python itself. It would be nice to keep it that way, although since Pylast is now pip installable it's not so important.

**Comment by IvanMalison** [comment]
The idea of adding the file to the project in raw to avoid dependencies is not particularly appealing to me. Including the file in the archive commits you as the pylast maintainer to manually handling copying new versions into the repository, which seems like a sloppy way to do things to me. I don't see a ton of value in not having dependencies, especially since as you mentioned, pylast is pip installable (or more accurately it is setuptools installable), which means that as long as you list the dependencies in the install_requires varaible, they are mostly transparent to the user.

I don't feel super strongly about this, and if you would prefer to add six as a file, I would happily make a PR to do so as the benefit of adding community supported/tested python2/3/unicode support far outweighs the downsides of manual dependency management.

**Comment by IvanMalison** [comment]
``` python
   @_string_output
    def __str__(self):
        return _unicode("%s - %s") % (
            self.get_artist().get_name(), self.get_title())
```

What is going on here... This seems pretty crazy to me. There is a unicode cast on a format string (which isn't a unicode string), and then a cast back to a normal byte string with a decorator...?

I would advocate something like what is prescribed in:
http://stackoverflow.com/questions/1307014/python-str-versus-unicode

where __str__ is just a wrapper around __unicode__ . In any case, the absence of a __unicode__ method, and the fact that this encodes to ut8 is what is causing the problem in this issue.

I honestly don't understand what _string and _unicode are trying to accomplish.

**Comment by hugovk** [comment]
Good point, let's just have six as a proper dependency instead of a raw file. Do you still think we need requirements.txt? If so, it should also go in there.
 
Pylast is mostly legacy code I've packaged up, tested and bugfixed so I'm more than happy for everything to be cleaned up, and the wrapper suggestion looks fine.

**Comment by IvanMalison** [comment]
No requirements.txt can go, that will be taken care of by the install_requirements=... in setup.py

tox can handle creating a virtualenv

**Comment by IvanMalison** [comment]
This is fixed and in master, right? I'm going to close

**Comment by hugovk** [comment]
I just merged https://github.com/pylast/pylast/pull/121 ("Merge develop to master") so yes, it's now in master.
