### ISSUE TITLE
Skip test_pylast.py if env vars not found

### ISSUE THREAD

**Issue by hugovk** [pylast/pylast#115]
I've re-enabled PR builds for https://travis-ci.org/pylast/pylast/

The integration tests test_pylast.py won't run on PRs because there are secure env variables.

test_pylast.py should be modified to just skip if the env vars can't be found rather than erroring/failing. That way at least the unit tests, which don't require env vars, can be run.

(Perhaps pylast should have a develop branch -- PRs can be merged into there, the integration tests run, and if passed, merged to master.)

**Comment by IvanMalison** [comment]
This can probably be handled by just properly implementing #105
