### ISSUE TITLE
Artist.get_correction()

### ISSUE THREAD

**Issue by myaa2913** [pylast/pylast#136]
I recently installed pylast via pip, and the `__init__.py` file was missing declaration of the get_correction method under the Artist class. I manually put the function back into my local file, but perhaps whatever files used during the pip installation need a fix?

**Comment by hugovk** [comment]
`Artist.get_correction()` (from https://github.com/pylast/pylast/pull/135) hasn't been released yet, so the pip installed version doesn't have it yet.

I'll make a release soon (probably when https://github.com/pylast/pylast/pull/134 is ready), in the meantime you should be able to install the dev version like this:

```bash
pip install git+git://github.com/pylast/pylast.git
```

**Comment by myaa2913** [comment]
thanks!

**Comment by hugovk** [comment]
Pylast version 1.3.0 is now released with `Artist.get_correction()`.

`pip install -U pylast`
