### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by jodal** [pylast/pylast#140]
I'm running pylast 1.0, but it seems like the same code is still present in the latest version in Git.

Sometimes, last.fm returns an error response without the `lfm` tag, and I get an `IndexError: list index out of range`:

``` python
Traceback (most recent call last):
  # ... my application's stack trace here ...
  File "/usr/lib/python2.7/dist-packages/pylast.py", line 713, in scrobble
    "stream_id": stream_id, "context": context, "mbid": mbid},))
  File "/usr/lib/python2.7/dist-packages/pylast.py", line 753, in scrobble_many
    _Request(self, "track.scrobble", params).execute()
  File "/usr/lib/python2.7/dist-packages/pylast.py", line 1134, in execute
    response = self._download_response()
  File "/usr/lib/python2.7/dist-packages/pylast.py", line 1125, in _download_response
    self._check_response_for_errors(response_text)
  File "/usr/lib/python2.7/dist-packages/pylast.py", line 1146, in _check_response_for_errors
    e = doc.getElementsByTagName('lfm')[0]
IndexError: list index out of range
```

**Comment by hugovk** [comment]
I've not seen that myself, and I'm using pylast for scrobbling from an [app](https://github.com/hugovk/bbcscrobbler) almost daily. (Although I do sometimes get `WSError`s but I don't think they're from scrobble calls and just ignore them.)

I'd guess Last.fm isn't returning a proper response. You could catch IndexErrors and try again, or to debug, put a `try`/`except` around `doc.getElementsByTagName('lfm')[0]` in pylast and print out what's in `doc`.

**Comment by jodal** [comment]
I see this maybe once a month, so that could take some time to get any results from...

**Comment by davea** [comment]
I'm seeing this too every once in a while. Captured the response from the server:
```
<html>Your request timed out.   Please retry the request.                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </html>
```

**Comment by hugovk** [comment]
So, a Last.fm server problem. Do you think it's better to catch this outside pylast, or catch it inside and throw a more specific exception?

**Comment by jodal** [comment]
I'd clearly prefer pylast to catch it and not have me care about anything else than `pylast.NetworkError`. Optionally, you can have `pylast.NetworkError` wrap the original exception, if any, so that those interested can dig into the outer exception to get more details.

If someone can reproduce the error again, it would be interesting to know what HTTP status code are returned with the response. It think it's better to check for e.g. 408 Request Timeout than just inferring the error case from an HTML document being returned instead of XML.

**Comment by hugovk** [comment]
Any updates on this?
