### ISSUE TITLE
user.get_top_artists ignoring period and limit params

### ISSUE THREAD

**Issue by laerm** [pylast/pylast#142]
_user.get_top_artists_ is ignoring _period_ and _limit_ parameters in my script and returns the default _overall_ and _unlimited_ (vs the _7day_ and _3_ I use to tweet my weekly chart).

I'm guessing this is due to last.fm's terrible upgrade which seems to have broken just about everything (what were they thinking??) but it seems to work for some users bizarrely:
https://getsatisfaction.com/lastfm/topics/api-stuff-that-works?topic-reply-list%5Bsettings%5D%5Bfilter_by%5D=all&topic-reply-list%5Bsettings%5D%5Bpage%5D=1#reply_16063890

Can you confirm the problem is on their side?

PS thanks for the great work!

**Comment by hugovk** [comment]
Those parameters appear to be working for me via the browser: http://www.last.fm/api/show/user.getTopArtists

But I get the exact same 50 results for `artists`, `artists2` and `artists3` with this, when they should be different:

```
import pylast
from pprint import pprint

API_KEY = TODO_ENTER_YOURS

network = pylast.LastFMNetwork(API_KEY)
user = network.get_user("RJ")

artists = user.get_top_artists()
pprint(artists)
print(len(artists))

artists2 = user.get_top_artists(period="7day")
pprint(artists2)
print(len(artists2))

print(artists == artists2)

artists3 = user.get_top_artists(period="7day", limit=3)
pprint(artists3)
print(len(artists3))

print(artists == artists3)
```

**Comment by laerm** [comment]
Glad you're getting the same behaviour as me. Guess we have to wait until they fix it :(

**Comment by hugovk** [comment]
I've not tested if it's also broken, but perhaps you can use http://www.last.fm/api/show/user.getWeeklyArtistChart in the meantime.

**Comment by laerm** [comment]
Thanks for the suggestion! It *nearly* does what I want. It returns the artists I've listened to in between those dates correctly but it returns the total playcount rather than the count from _from_ to _to_. Another last.fm API fail or is this expected (the documentation is rather vague)?

**Comment by 19379** [comment]
i'm not a pylast user but i got here via the thread on last.fm's forums and i think this issue is caused by using POST requests and sending parameters as post data rather than GET with parameters appended to the url. that's why the examples on the doc pages work and i'm not having any problems with the methods listed either.

given the docs say we should only be using POST for authenticated services, i'm not sure if last.fm are going to restore this functionality. even if they do, it could be a long time coming!!

http://www.last.fm/api/rest

**Comment by hugovk** [comment]
@19379 Thanks very much for the suggestion, that looks like it!

@laerm I'm not sure when I'll get time to fix the library properly, but if you want a quick and dirty hack to get you up and running, change [this line](https://github.com/pylast/pylast/blob/develop/pylast/__init__.py#L1116) in `_download_response()` from:

                        method='POST', url=HOST_SUBDIR, body=data, headers=headers)

to:

                        method='GET', url=HOST_SUBDIR + "?" + data)

When I run it with this:

```python
import pylast

API_KEY = TODO_ENTER_YOURS

network = pylast.LastFMNetwork(API_KEY)
user = network.get_user("RJ")

artists3 = user.get_top_artists(period="7day", limit=3)
print(len(artists3))
for artist in artists3:
    print(artist.item.name, artist.weight)
```

I get:
```
(u'Mayer Hawthorne', u'102')
(u'Submotion Orchestra', u'66')
(u'Bonobo', u'24')
```

Which corresponds to http://www.last.fm/api/show/user.getTopArtists

**Comment by 19379** [comment]
you could probably implement a better hack that doesn't break authenticated/write services. you can do that by checking the **data** to see if contains **api_sig**. use POST or GET depending on the result.

**Comment by hugovk** [comment]
Thanks, I've done that in this branch:

https://github.com/hugovk/pylast/tree/post_or_get

**Comment by dddanmar** [comment]
@hugovk thank you for the post_or_get branch, I'm now unstuck and can keep working!

**Comment by laerm** [comment]
@hugovk thanks for the branch, have got it working properly now!
