### ISSUE TITLE
.get_now_playing() stopped working after last.fm update.

### ISSUE THREAD

**Issue by skewerr** [pylast/pylast#143]
I'm always getting None, regardless of scrobbling a track for now playing or not. I checked your [post_or_get](https://github.com/hugovk/pylast/tree/post_or_get) branch and even then it fails.

Through py.test, 72 methods fail.

**Comment by hugovk** [comment]
pylast is getting useful data back from Last.fm, you can check by printing out `response_text` after this line:
```python
response_text = _unicode(conn.getresponse().read())
```

But something has changed meaning pylast isn't handling it properly. In fact, this is a duplicate of #141 because user.get_now_playing() just filters the results of user.get_recent_tracks().

**Comment by hugovk** [comment]
I have a fix for #141 (in PR https://github.com/pylast/pylast/pull/144) but the Last.fm API is still broken: `user.getRecentTracks` is still missing the `nowplaying="true"` attribute. 

Test it here: http://www.last.fm/api/show/user.getRecentTracks

Already reported to Last.fm here, give it a "like": https://getsatisfaction.com/lastfm/topics/api-known-issues?topic-reply-list%5Bsettings%5D%5Bfilter_by%5D=all&topic-reply-list%5Bsettings%5D%5Breply_id%5D=16021759#reply_16021759

**Comment by skewerr** [comment]
I see. My bad. I see it's already fixed.

**Comment by hugovk** [comment]
No problem, it's better to report than not to. 

Thanks for mentioning the `nowplaying` thing has been fixed on Last.fm's side too.

#141 has been fixed in newly-released pylast 1.4.1.
