### ISSUE TITLE
malformed response error from ArtistSearch.get_next_page()

### ISSUE THREAD

**Issue by yanggao1119** [pylast/pylast#152]
Hi,

I am using the latest pylast package, and got malformed response error when I tried to call `get_next_page()` on an `ArtistSearch` object.

Here is the error:

```
Traceback (most recent call last):
  File "debug_get_next_page.py", line 13, in <module>
    result = artistsearch_obj.get_next_page()
  File "build/bdist.macosx-10.10-intel/egg/pylast/__init__.py", line 3839, in get_next_page
  File "build/bdist.macosx-10.10-intel/egg/pylast/__init__.py", line 3805, in _retrieve_next_page
  File "build/bdist.macosx-10.10-intel/egg/pylast/__init__.py", line 3799, in _retrieve_page
  File "build/bdist.macosx-10.10-intel/egg/pylast/__init__.py", line 1308, in _request
  File "build/bdist.macosx-10.10-intel/egg/pylast/__init__.py", line 1136, in execute
  File "build/bdist.macosx-10.10-intel/egg/pylast/__init__.py", line 1127, in _download_response
  File "build/bdist.macosx-10.10-intel/egg/pylast/__init__.py", line 1146, in _check_response_for_errors
pylast.MalformedResponseError: Malformed response from Last.fm. Underlying error: unbound prefix: line 2, column 41
```

And code to reproduce the error:

```python
import pylast

api_key = $API_KEY
api_secret = $API_SECRET
username = $USERNAME
password = $PASSWORD
network = pylast.LastFMNetwork(api_key = api_key,
					api_secret = api_secret,
					username = username,
					password_hash = pylast.md5(password))

artistsearch_obj = network.search_for_artist("Coldplay")
result = artistsearch_obj.get_next_page()
```

**Comment by hugovk** [comment]
Last.fm broke their API about a month ago and there's still lots of broken things; `artist.search` amongst them. For example, I get errors from their example URLs here: http://www.last.fm/api/show/artist.search

```
This page contains the following errors:

error on line 2 at column 103: Namespace prefix opensearch on Query is not defined
error on line 3 at column 25: Namespace prefix opensearch on totalResults is not defined
error on line 4 at column 23: Namespace prefix opensearch on startIndex is not defined
error on line 5 at column 25: Namespace prefix opensearch on itemsPerPage is not defined
Below is a rendering of the page up to the first error.
```

Last.fm say this is a known issue here:
https://getsatisfaction.com/lastfm/topics/api-known-issues

(If pylast can be made more robust to handle errors better, PRs are welcome, but it shouldn't break Libre.fm support. Also "Malformed response" sounds about right for the current Last.fm server-side problems.)

**Comment by yanggao1119** [comment]
Hi,

I am very confused about what you said... It seems to me more like a
problem with pylast, not last.fm. The reason is that when I directly use
the Example URL that last.fm provides, with my api_key, I can get the right
response with this:

http://ws.audioscrobbler.com/2.0/?method=artist.search&artist=cher&api_key=MY_KEY&format=json

Yang Gao
213.618.2259 | yanggao1119@gmail.com

On Sat, Sep 19, 2015 at 7:50 AM, Hugo van Kemenade <notifications@github.com

**Comment by yanggao1119** [comment]
I can understand what you said now! It is the problem of xml parser. Therefore, if i don't specify son, the default xml output will give errors. So, is there a way for modifying pylast to specify json and parse json?

http://ws.audioscrobbler.com/2.0/?method=artist.search&artist=Coldplay&api_key=MY_KEY

**Comment by hugovk** [comment]
In theory pylast could be modified to use JSON, but it'd be a fair amount of work to update and test the parsing, especially given we don't know if all the JSON-format services are working, and there's definitely some things broken in both. 

However, PRs are welcome. One option is to modify and test pylast just enough to get things like `artist.search` working in the short term and just keep it on a branch.

**Comment by yanggao1119** [comment]
Hi Hugo,

what do you mean by PR? Currently we have problem with the opensearch
namespace, which last.fm introduced but somehow has not taken proper care
of.

A quick and dirty way to fix this is to replace the string 'opensearch:' as
empty string, in xml response, and send that to minidom.parseString, thus
the following:

        return minidom.parseString(_string(response).*replace*('opensearch:',
''))

            doc =
minidom.parseString(_string(response).*replace*('opensearch:',
''))


it seems to work for me.

Yang Gao
213.618.2259 | yanggao1119@gmail.com

**Comment by yanggao1119** [comment]
i sent a pull request to pylast:develop ; quick and easy fix. could you check if that works?

**Comment by hugovk** [comment]
PR https://github.com/pylast/pylast/issues/153 has been merged. Thanks!
