### ISSUE TITLE
Error when calling get_top_fans() on artist object

### ISSUE THREAD

**Issue by hannibunny** [pylast/pylast#155]
I got an error when calling the get_top_fans() method on an artist object - everything else still works fine, just this error in this method.
The error message is in the attached screenshot. 

![get_top_fanserror](https://cloud.githubusercontent.com/assets/1442821/10221247/86906b86-684d-11e5-940c-55f73ad97191.PNG)

**Comment by hugovk** [comment]
Thanks for the report. Last.fm broke their API six weeks ago and there's still lots of broken things; `artist.getTopFans` amongst them. For example, I get errors from their example URLs here: http://www.last.fm/api/show/artist.search

```xml
<lfm status="failed">
  <error code="3">Invalid Method - No method with that name in this package</error>
</lfm>
```

I've reported this to Last.fm:
https://getsatisfaction.com/lastfm/topics/api-known-issues?topic-reply-list%5Bsettings%5D%5Bfilter_by%5D=all&topic-reply-list%5Bsettings%5D%5Breply_id%5D=16176464#reply_16176464

(If pylast can be made more robust to handle errors better, PRs are welcome, but it shouldn't break Libre.fm support. But the error it's gicing sounds about right for the current Last.fm server-side problems.)

**Comment by hugovk** [comment]
It's been long enough and Last.fm still haven't fixed it, so this will be removed in the next pylast release.
