### ISSUE TITLE
how to start pylast

### ISSUE THREAD

**Issue by xgate1** [pylast/pylast#156]
I start pylast today and I try to run "Getting Started" code but  i can't get api key, api key secrete
lastfm no more provide api key
how to run without api key?
I have lastfm id only.

Code:
```python
import pylast


API_KEY = "b25b959554ed76058ac220b7b2e0a026" # this is a sample key
API_SECRET = "425b55975eed76058ac220b7b4e8a054"


username = "your_user_name"
password_hash = pylast.md5("your_password")

network = pylast.LastFMNetwork(api_key = API_KEY, api_secret =
    API_SECRET, username = username, password_hash = password_hash)


artist = network.get_artist("System of a Down")
artist.shout("<3")


track = network.get_track("Iron Maiden", "The Nomad")
track.love()
track.add_tags(("awesome", "favorite"))
```

**Comment by hugovk** [comment]
Last.fm updated their website and somehow at the same time broke lots of the API, including the new API key signup, which is still broken over two months later. 

They know about it, but you can try posting in their support forum:

https://getsatisfaction.com/lastfm/topics/trying-to-apply-for-an-api-key

https://getsatisfaction.com/lastfm/topics/api-known-issues

And keep an eye out for updates in the forum too.

**Comment by xgate1** [comment]
thanks

**Comment by hugovk** [comment]
You should be able to create new API accounts, but beware a lot of the API is still broken:

https://getsatisfaction.com/lastfm/topics/api-account-creation-re-enabled
