### ISSUE TITLE
Error when creating an album with ' in name

### ISSUE THREAD

**Issue by gnumdk** [pylast/pylast#165]
```python
>>> lastfm = pylast.LastFMNetwork(api_key=_API_KEY, api_secret=_API_SECRET)
>>> album=lastfm.get_album("Prohiber", "Pov'typ")
>>> album.get_cover_image(4)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/pylast/__init__.py", line 1842, in get_cover_image
    self.ws_prefix + ".getInfo", cacheable=True), 'image')[size]
  File "/usr/lib/python3.5/site-packages/pylast/__init__.py", line 4118, in _extract_all
    seq.append(_extract(node, name, i))
  File "/usr/lib/python3.5/site-packages/pylast/__init__.py", line 4073, in _extract
    return _unescape_htmlentity(nodes[index].firstChild.data.strip())
AttributeError: 'Element' object has no attribute 'data'
```

**Comment by hugovk** [comment]
Thanks for the bug report.

There are two problems here.

1) `get_cover_image` calls `album.getInfo` in Last.fm's API, which just returns empty values for images:

```xml
<image>
<size>small</size>
</image>
<image>
<size>medium</size>
</image>
<image>
<size>large</size>
</image>
<image>
<size>extralarge</size>
</image>
<image>
<size>mega</size>
</image>
```
You can test this here: http://www.last.fm/api/show/album.getInfo

This sort of makes sense, as there doesn't appear to be any album art on the website: http://www.last.fm/music/Prohiber/Pov%27Typ

2) pylast shouldn't raise an exception here, and should probably instead return None.

Last.fm changed their website 6 months ago, and removed lots of stuff, and at the same time broke lots of their API. They're still -- slowly -- fixing it. I have a feeling that before Last.fm wouldn't even return these essentially empty images tags before, and so pylast would work smoothly, but I can't be sure.

Anyway, this deserves a fix in pylast.

**Comment by hugovk** [comment]
I was going to fix this but pylast is now working. `album.get_cover_image(4)` returns None.

Last.fm have fixed their XML and it now looks like this:

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<lfm status="ok"><album><name>Pov&apos;Typ</name>
<artist>Prohiber</artist>
<url>http://www.last.fm/music/Prohiber/Pov%27Typ</url>
<image size="small"></image>
<image size="medium"></image>
<image size="large"></image>
<image size="extralarge"></image>
<image size="mega"></image>
<image size=""></image>
<listeners>2</listeners>
<playcount>11</playcount>
<tracks></tracks>
<tags></tags>
</album>
</lfm>
```

So I'll put this down to a temporary Last.fm error and won't change pylast. Let me know if it comes up again.
