### ISSUE TITLE
how to get past geo top artist?

### ISSUE THREAD

**Issue by xgate1** [pylast/pylast#174]
i need past geo top artist
now i get current geo top artist 
ex> 2016/ 5 spain geo top artist
but, i want get past geo top artists
ex>2015 4 16
pls, give me some tips

**Comment by hugovk** [comment]
You can get current geo top artists like this:
```python
artists = self.network.get_geo_top_artists(
            country="United Kingdom", limit=1)
```

**Comment by hugovk** [comment]
You can get current geo top artists like this:
```python
artists = self.network.get_geo_top_artists(
            country="United Kingdom", limit=1)
```

You used to be able to get weekly charts for a metro (a city) like this:
```python
        metro = self.network.get_metro("Madrid", "Spain")
        dates = self.network.get_metro_weekly_chart_dates()
        (from_date, to_date) = dates[0]

        # get metro.function_name()
        func = getattr(metro, function_name, None)

        # Act
        chart = func(from_date=from_date, to_date=to_date, limit=1)
```

But it looks like Last.fm have removed that after they relaunched ("re-imagined") their website last August and broke lots of functionality.

Have a look through the available list of methods here: http://www.last.fm/api If it's not there, it's not available in pylast. If it is there, it should be available here too (and should be addable if not yet here).

**Comment by xgate1** [comment]
thanks
