### ISSUE TITLE
Scrobble with timestamps in the past

### ISSUE THREAD

**Issue by jorgt** [pylast/pylast#175]
Hi, 

More of a question than an issue. 

I'm trying to backdate a few scrobbles in an attempt to merge accounts (turns out I had two). One of them has a few thousand songs recorded in 2007. 

A line like this throws no errors and seems to go through just fine. I just have no scrobbled record there. 

```
network.scrobble(artist="M. Ward", title="Right in the Head", timestamp=1162133400 , album="M. Ward")
```

works OK when I replace it with a newer timestamp, like ```int(time.time())```, floats right to the top of the "last played" list. 

Anyone know if there's a limit?

**Comment by hugovk** [comment]
Unfortunately Last.fm has a [two-week limit on scrobbles](http://www.last.fm/forum/21713/_/455659/1#f7277323):

> Yes, due to the way we calculate charts, and also to prevent being "spammed" with false data, we do not accept scrobbles that are more than 14 days old.

[Because](http://www.last.fm/forum/21713/_/455659/1#f7342315):

> unfortunately it's not really practical to totally remove that limit. We get an enormous amount of data sent to us and we have to process this data which takes up a lot of computing power (and time). Without going into all the technical details, allowing older scrobbles makes the data crunching a lot slower as we have to go back and update all kinds of old datasets, charts etc. Imagine someone now submitting a track from 2004 and us having to go back and update all the affected weekly, monthly, 3-monthly, 6-monthly and yearly charts. As it stands we now only have to do 2 weeks of backdating which we chose as a compromise between allowing old data and the extra computations required.

**Comment by jorgt** [comment]
Thanks for the info.
