### ISSUE TITLE
pylast.User.get_neighbours() Invalid Method - No method with that name in this package

### ISSUE THREAD

**Issue by tyrostone** [pylast/pylast#180]
An exception occurs when I use the `get_neighbours()` method on the User object.

``` python
>>> network = pylast.LastFMNetwork(api_key=API_KEY, api_secret=SECRET, username=username, password_hash=password)
>>> user = network.get_user(username)
>>> user.get_neighbours()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/user/.virtualenvs/lastfm/lib/python2.7/site-packages/pylast/__init__.py", line 3342, in get_neighbours
    self.ws_prefix + '.getNeighbours', cacheable, params)
  File "/Users/user/.virtualenvs/lastfm/lib/python2.7/site-packages/pylast/__init__.py", line 1311, in _request
    return _Request(self.network, method_name, params).execute(cacheable)
  File "/Users/user/.virtualenvs/lastfm/lib/python2.7/site-packages/pylast/__init__.py", line 1137, in execute
    response = self._download_response()
  File "/Users/user/.virtualenvs/lastfm/lib/python2.7/site-packages/pylast/__init__.py", line 1128, in _download_response
    self._check_response_for_errors(response_text)
  File "/Users/user/.virtualenvs/lastfm/lib/python2.7/site-packages/pylast/__init__.py", line 1157, in _check_response_for_errors
    raise WSError(self.network, status, details)
pylast.WSError: Invalid Method - No method with that name in this package
```

I am using version 1.6.0

**Comment by hugovk** [comment]
Thanks for the report. Unfortunately Last.fm redesigned ("reimagined") their website in August 2015 and also broke their API. They've been slowly adding things back, but there still remains lots of broken stuff. They've also removed a lot from their API docs page, and we don't know if they're coming back. 

pylast's `User.get_neighbours ` calls Last.fm's `user.getNeighbours`:

https://github.com/pylast/pylast/blob/develop/pylast/__init__.py#L3334-L3350

They removed it from their docs at http://www.last.fm/api sometime after January 2016:

https://web.archive.org/web/20160113041418/http://www.last.fm/api
https://web.archive.org/web/20151023082634/http://www.last.fm/api/show/user.getNeighbours

I've reported this to Last.fm:
https://getsatisfaction.com/lastfm/topics/user-getneighbours-invalid-method-no-method-with-that-name-in-this-package

**Comment by unusual-thoughts** [comment]
In the meantime, neighbours can be scraped from html, no authentication needed:
[https://gist.github.com/unusual-thoughts/2b82d67577da6cd0feacd4c764db4998](url)

**Comment by hugovk** [comment]
It's been long enough and it's still missing from Last.fm so pylast.User.get_neighbours() will be removed in the next release.
