### ISSUE TITLE
"pylast.MalformedResponseError" with librefm

### ISSUE THREAD

**Issue by temrix** [pylast/pylast#186]
I get this error:
`pylast.MalformedResponseError: Malformed response from Last.fm. Underlying error: no element found: line 1, column 0`
when trying to login into libre.fm while I’m using Lollypop.

I already reported the error here: https://github.com/gnumdk/lollypop/issues/873
but it seems to be an issue with pylast (or libre.fm api is broken).

**Comment by hugovk** [comment]
I won't be able to investigate this for a while, but this unmerged PR might help.

https://github.com/pylast/pylast/pull/179/files

You could try installing from that PR branch, or just modify the URL in the pylast source and try again.

**Comment by temrix** [comment]
I tried both and nothing worked so I think it must be an API issue. I will notify them on their bugtracker.

**Comment by hugovk** [comment]
Thanks. 

Here's an example of a working API call with the new URL: https://libre.fm/2.0/?method=artist.getinfo&artist=radiohead

I'll fix the test for PR #179 and make a new release.

**Comment by hugovk** [comment]
Pylast 1.7.0 is now released.
