### ISSUE TITLE
Track.get_album() returns None instead of the Album object

### ISSUE THREAD

**Issue by selib** [pylast/pylast#190]
this happens for every track ive tried it with

**Comment by hugovk** [comment]
Please can you give an example?

Which Python and pylast version?

Does it happen with the previous pylast version?

**Comment by selib** [comment]
Python 3.6
Pylast 1.7.0

Actually I think i solved this. didn't realize I had to call

```
user = network.get_user("selib")
recent_tracks = user.get_recent_tracks(limit=3)
recent_tracks[0].track.get_album()
```

I was always calling

`recent_tracks[0].get_album()`
which returned None

but I was rightfully confused because

```
top_tracks = user.get_top_tracks(limit=3)
top_tracks [0].get_album()
```

actually returned the right album


Although another problem I run into was calling on the Daft Punk - One More Time track object 
recent_tracks[0].track.get_album()
returning DJ geoffe - Best of Club Hits, Volume 1
instead of Daft Punk - Discovery which I listened One More Time on. but i assume that's a last.fm issue

**Comment by hugovk** [comment]
Yes, that'll be a Last.fm data issue.

**Comment by ranguera** [comment]
i have that issue too (making the right call i.e. _print(data[i].track.get_album())_
for instance:
- http://www.last.fm/music/richard%2bskelton/_/the%2bblack%2bdub
- http://www.last.fm/music/jean%2bmichel%2bjarre/_/a%2bquestion%2bof%2bblood

return None, while they have an associated album on the lastfm page. Other tracks return the correct album object

**Comment by ranguera** [comment]
i should add that creating the album object from track data track.artist, track.album (string) does return the correct album object. ex:

al = pylast.Album(data[0].track.artist,data[0].album,lastfm_network)
