### ISSUE TITLE
Track.get_top_tags() returns different tags even though Last.fm returns correct tags

### ISSUE THREAD

**Issue by GauthamGoli** [pylast/pylast#192]
`http://ws.audioscrobbler.com/2.0/?method=track.getInfo&api_key=<insert_your_key>&artist=Major%20Lazer%20feat.%20Justin%20Bieber%20&%20M%C3%98&track=Cold%20Water&format=json`

returns

 `{"track":{"name":"Cold Water","url":"https://www.last.fm/music/Major+Lazer+feat.+Justin+Bieber+/_/Cold+Water","duration":"0","streamable":{"#text":"0","fulltrack":"0"},"listeners":"0","playcount":"0","artist":{"name":"Major Lazer feat. Justin Bieber ","url":"https://www.last.fm/music/Major+Lazer+feat.+Justin+Bieber+"},"toptags":{"tag":[{"name":"party","url":"https://www.last.fm/tag/party"},{"name":"featuring","url":"https://www.last.fm/tag/featuring"},{"name":"uk number one","url":"https://www.last.fm/tag/uk+number+one"},{"name":"2016 single","url":"https://www.last.fm/tag/2016+single"},{"name":"bbc radio1 playlist 2016","url":"https://www.last.fm/tag/bbc+radio1+playlist+2016"}]}}}`

`"toptags"` shows `"party"` as one of the tags.

Whereas making the same API call from the pylast module returns different tags.
```python
track_object = pylast.network.get_track("Major Lazer feat. Justin Bieber & MØ", "Cold Water")
track_object.get_top_tags()
```

`track_object.get_top_tags()` returns `'featuring', 'uk number one', 'playlista rmf fm', '2016 single'`

can you please fix this?

**Comment by hugovk** [comment]
I don't think this is a pylast bug, rather you're submitting an incorrectly encoded artist name in the first example, in particular the unescaped `&` causes the problem and should be `%26`.

---

If you look at the JSON results from your first link, you'll see it gives an artist name like this:
```json
url: "https://www.last.fm/music/Major+Lazer+feat.+Justin+Bieber+/_/Cold+Water",
duration: "0",
...
listeners: "0",
playcount: "0",
...
artist: {
name: "Major Lazer feat. Justin Bieber ",
url: "https://www.last.fm/music/Major+Lazer+feat.+Justin+Bieber+"
},
```

---

If you URL encode (e.g. with http://www.url-encode-decode.com) "Major Lazer feat. Justin Bieber & MØ" you get `Major+Lazer+feat.+Justin+Bieber+%26+M%C3%98`. 

Sticking that in your first URL gives:

`http://ws.audioscrobbler.com/2.0/?method=track.getInfo&api_key=<insert_your_key>&artist=Major+Lazer+feat.+Justin+Bieber+%26+M%C3%98&track=Cold%20Water&format=json`

Resulting in the correct artist name:
```json
url: "https://www.last.fm/music/Major+Lazer+feat.+Justin+Bieber+&+M%C3%98/_/Cold+Water",
duration: "183000",
...
listeners: "1492",
playcount: "7014",
...
artist: {
name: "Major Lazer feat. Justin Bieber & MØ",
url: "https://www.last.fm/music/Major+Lazer+feat.+Justin+Bieber+&+M%C3%98"
}
```
And the top tags match those returned by your pylast code.

**Comment by GauthamGoli** [comment]
Thanks!
