### ISSUE TITLE
Does this library provide Last.fm callback support?

### ISSUE THREAD

**Issue by jacebrowning** [pylast/pylast#193]
I am using Last.fm to authenticate users in a Django application and expect Last.fm to send my application a [callback with a temporary authentication token](http://www.last.fm/api/webauth). I am unclear how to do this with `pylast`. The closest API appears to be [SessionKeyGenerator. get_web_auth_session_key(url)](https://github.com/pylast/pylast/blob/7b3ab250df752caeba712b48be1e760bfdbc9983/pylast/__init__.py#L1307), but that doesn't actually extract the token from the callback URL.

I ended up doing it manually using `_Request`:

```python
token = request.GET.get('token')  # Django request  object

network = pylast.LastFMNetwork(
    api_key=LASTFM_API_KEY,
    api_secret=LASTFM_API_SECRET,
)

call = pylast._Request(network, 'auth.getSession', {'token': token})
call.sign_it()

try:
    xml = call.execute()
except pylast.WSError as exc:
    log.error(exc)
    return None
else:
    return xml
```

Did I miss an API that provides similar functionality? Would you consider a PR that provides this functionality?

**Comment by hugovk** [comment]
No, pylast doesn't have such a function. Yes, I would consider a PR. Thanks!

**Comment by jacebrowning** [comment]
Would you consider allowing `LastFMNetwork` to accept an option `token` argument?

```python
import pylast
from django.conf import settings

def index(request):
    token = request.GET.get('token')
    network = pylast.LastFMNetwork(
        api_key=settings.LASTFM_API_KEY,
        api_secret=LASTFM_API_SECRET,
        token=token,  # <-- new option auth token
    )
    
    return render(request, 'index.html', {'username': network.username})
```

**Comment by hugovk** [comment]
Sure. Would you like to create a PR with tests so we can see the whole thing? 

https://github.com/pylast/pylast#testing

It'd be good to enable Travis CI for your fork, and add your test keys to the Travis CI settings, or even encode them in the .travis.yml so they're their for PRs on this repo's builds too: https://github.com/pylast/pylast/blob/develop/.travis.yml#L4

**Comment by jacebrowning** [comment]
Yeah, I'll put something together.
