### ISSUE TITLE
get_top_fans() --WSError: Invalid Method - No method with that name in this package

### ISSUE THREAD

**Issue by Luxios** [pylast/pylast#197]
```
WSError                                   Traceback (most recent call last)
<ipython-input-48-f7e9f7e9b311> in <module>()
----> 1 top_tracks[0][0].get_top_fans()

D:\Study\Python\Anaconda2\lib\site-packages\pylast\__init__.pyc in get_top_fans(self, limit, cacheable)
   1440         """
   1441 
-> 1442         doc = self._request(self.ws_prefix + '.getTopFans', cacheable)
   1443 
   1444         seq = []

D:\Study\Python\Anaconda2\lib\site-packages\pylast\__init__.pyc in _request(self, method_name, cacheable, params)
   1394             params = self._get_params()
   1395 
-> 1396         return _Request(self.network, method_name, params).execute(cacheable)
   1397 
   1398     def _get_params(self):

D:\Study\Python\Anaconda2\lib\site-packages\pylast\__init__.pyc in execute(self, cacheable)
   1220             response = self._get_cached_response()
   1221         else:
-> 1222             response = self._download_response()
   1223 
   1224         return minidom.parseString(_string(response).replace(

D:\Study\Python\Anaconda2\lib\site-packages\pylast\__init__.pyc in _download_response(self)
   1211         response_text = XML_ILLEGAL.sub("?", response_text)
   1212 
-> 1213         self._check_response_for_errors(response_text)
   1214         return response_text
   1215 

D:\Study\Python\Anaconda2\lib\site-packages\pylast\__init__.pyc in _check_response_for_errors(self, response)
   1240             status = e.getAttribute('code')
   1241             details = e.firstChild.data.strip()
-> 1242             raise WSError(self.network, status, details)
   1243 
   1244 

WSError: Invalid Method - No method with that name in this package
```

**Comment by hugovk** [comment]
Thanks for the report. Unfortunately Last.fm redesigned ("reimagined") their website in August 2015 and also broke their API. They've been slowly adding things back, but there still remains lots of broken stuff. They've also removed a lot from their API docs page, and we don't know if they're coming back. 

pylast's `Track. get_top_fans ` calls Last.fm's `track. getTopFans`:
https://github.com/pylast/pylast/blob/develop/pylast/__init__.py#L1442

They removed it from their docs at http://www.last.fm/api sometime after January 2016:
https://web.archive.org/web/20160113041418/http://www.last.fm/api
https://web.archive.org/web/20151226015136/http://www.last.fm/api/show/track.getTopFans

Please report this to Last.fm:
https://getsatisfaction.com/lastfm/categories/lastfm_api

Here's another for reference:
https://getsatisfaction.com/lastfm/topics/user-getneighbours-invalid-method-no-method-with-that-name-in-this-package

**Comment by Luxios** [comment]
Thanks.Is there any method to get the users?

**Comment by hugovk** [comment]
If it's not on http://www.last.fm/api/ then it's not here.

Your other options would be to scrape the Last.fm website directly using something like [Beautiful Soup](https://www.crummy.com/software/BeautifulSoup/).

**Comment by hugovk** [comment]
It's been long enough and Last.fm still haven't fixed it, so this will be removed in the next pylast release.
