### ISSUE TITLE
remove_scrobble removed from API

### ISSUE THREAD

**Issue by casey** [pylast/pylast#199]
It looks like the removeScrobble method has been removed from the last.fm API

**Comment by hugovk** [comment]
Yes, Last.fm redesigned ("reimagined") their website in August 2015 and also broke their API. They've been slowly adding things back, but there still remains lots of broken stuff. They've also removed a lot from their API docs page, and we don't know if they're coming back. 

They removed it from their docs at http://www.last.fm/api sometime on 14 January 2016:
https://web.archive.org/web/20160114204951/http://www.last.fm/api
https://web.archive.org/web/20160114204951/http://www.last.fm/api

This has already been reported here, leave a comment and me-too if you'd like it fixed:
https://getsatisfaction.com/lastfm/topics/are-there-any-plans-to-add-back-the-library-removescrobble-method-to-the-api

**Comment by casey** [comment]
Super weird. It seems like a really basic method.

Is there any speculation as to why they removed the method? Could they be worried about giving users the ability to remove scrobbles en masse?

I commented and me-too-ed, for what it's worth :-/

**Comment by hugovk** [comment]
It seems like the whole API broke when they "reimagined" the website and they've had to reimplement everything from scratch.

Thanks for the comment and me-too.

**Comment by casey** [comment]
It's always tempting to rewrite everything from scratch, but pretty dangerous. It's always more work than you think it is ;_;

Thanks for this library by the way!

**Comment by hugovk** [comment]
It's been long enough and Last.fm still haven't fixed it, so this will be removed from the next pylast release. We can add it back if they ever add it back.
