### ISSUE TITLE
track.getSimilar is missing the limit parameter

### ISSUE THREAD

**Issue by redshodan** [pylast/pylast#249]
### What did you do?
Try to use the limit parameter for track.getSimilar

### What did you expect to happen?
The query to work.

### What actually happened?
The function call fails because it doesn't have the limit parameter.

### What versions of OS, Python and pylast are you using?
Python 3.6, OS/X 10.12, pylast 2.1.0 and master

I have a PR for this ready to submit.

**Comment by redshodan** [comment]
For a code example: https://github.com/redshodan/unsonic/blob/lastfm/unsonic/views/rest/getsimilarsongs.py#L34-L38

**Comment by hugovk** [comment]
Thanks for the PR! By the way, this link is 404 for me.

**Comment by redshodan** [comment]
That would be because I merged that branch and deleted right after I put the link here. :) https://github.com/redshodan/unsonic/blob/master/unsonic/views/rest/getsimilarsongs.py#L34-L38

**Comment by hugovk** [comment]
pylast 2.2.0 is now released with the fix.

**Comment by redshodan** [comment]
Excellent, thank you!
