### ISSUE TITLE
Use Markdown on PyPI

### ISSUE THREAD

**Issue by hugovk** [pylast/pylast#256]
When https://github.com/pypa/wheel/pull/232 is released, add long_description_content_type='text/markdown' to use Markdown on PyPI. 

For instructions, see:
* https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi
* https://github.com/di/markdown-description-example

**Comment by shakefu** [comment]
Is this supposed to work already on `pypi.org`? My project doesn't seem to be rendering correctly on the Warehouse or Legacy (though libraries.io has no issue - so it's not a Markdown syntax thing.)

**Comment by hugovk** [comment]
Wheel is released https://pypi.org/project/wheel/0.31.0/
