### ISSUE TITLE
if nodes[index].firstChild: IndexError: list index out of range

### ISSUE THREAD

**Issue by Taiko2k** [pylast/pylast#266]
### What did you do?
Attempt to use `get_loved_tracks(Limit=None)` on a certain profile

The method crashes with error

```python
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    loves = user.get_loved_tracks(limit=None)
  File "/home/kai/Desktop/pylast/__init__.py", line 2208, in get_loved_tracks
    artist = _extract(track, "name", 1)
  File "/home/kai/Desktop/pylast/__init__.py", line 2721, in _extract
    if nodes[index].firstChild:
IndexError: list index out of range

```
I've tested a number of profiles but I've only found this one profile that triggers the crash.

### What versions of OS, Python and pylast are you using?
Arch Linux, Python 3.6.5, Tested both pylast 2.2 and Master

```python
import pylast
network = pylast.LastFMNetwork(api_key="REMOVED", api_secret="REMOVED")
user = network.get_user("Askefrost")
loves = user.get_loved_tracks(limit=None)
```
I tried to debug this, I noticed that the dom element xml didn't have a title name when it hit the track https://www.last.fm/music/aran/_/Rusted+Dream that it seems to crash on. But I'm not familiar this kind of thing.

**Comment by hugovk** [comment]
Thanks for the report, I can reproduce it and will have a look.

**Comment by hugovk** [comment]
Please see PR https://github.com/pylast/pylast/pull/268 with a fix.

**Comment by Taiko2k** [comment]
That's interesting, does seem to be a bit of an anomaly there. Thanks for the explanation and responding with a fix so quickly!
