### ISSUE TITLE
Release history?

### ISSUE THREAD

**Issue by jacebrowning** [pylast/pylast#273]
I was looking for a changelog or history of released versions, but I couldn't find it.

**Comment by hugovk** [comment]
There isn't a changelog, other than the version requirements in https://github.com/pylast/pylast/blob/master/README.md#installation and the commits list at https://github.com/pylast/pylast/commits/master, or commits between versions like https://github.com/pylast/pylast/compare/2.2.0...2.3.0, which aren't very readable or useful. 

You can see a history of releases and their dates at https://github.com/pylast/pylast/releases and https://pypi.org/project/pylast/#history. 

I should start a changelog. Thanks!
