### ISSUE TITLE
AuthenticatedUser.get_name() now returns an empty string

### ISSUE THREAD

**Issue by jacebrowning** [pylast/pylast#274]
### What did you do?

One of my applications started experiencing 500s of:

> Operation failed - Most likely the backend service failed. Please try again.

So I upgraded from `1.9.0` to `2.3.0` assuming there must have been a change to the Last.fm API that broke my deployed application.

```python
>>> network = pylast.LastFMNetwork(
    api_key=LASTFM_API_KEY,
    api_secret=LASTFM_API_SECRET,
    token=TOKEN_GENERATED_BY_LASTFM,
)
>>> user = network.get_authenticated_user()
>>> user.get_friends()[0].name
'janedoe'
>>> user.name
''
>>> user.get_name()
''
```

### What did you expect to happen?

`AuthenticatedUser.get_name()` used to return the username.

### What actually happened?

`AuthenticatedUser.get_name()` now returns an emptry string.

### What versions of OS, Python and pylast are you using?

- macOS 10.13.5
- Python 3.6.3
- pylast 2.3.0

**Comment by hugovk** [comment]
I saw the same `Operation failed - Most likely the backend service failed. Please try again.` recently when the CI started failing and also assumed it was an API change. I fixed it in https://github.com/pylast/pylast/pull/269/commits/000993c3289405c9d5a50c896c47795a52075608 in #269, released in pylast 2.3.0.

I've just tested with your code and both `user.name` and `user.get_name()` return the correct value.

* macOS 10.13.5
* Python 3.6.5
* pylast 2.3.0

However, I created the `network` like this, and not with a token:

```python
network = pylast.LastFMNetwork(api_key=API_KEY, api_secret=API_SECRET,
                               username=username, password_hash=password_hash)
```

I'll check with a token later, but in the meantime please can you let me know if it works for you with a username and password hash?

**Comment by hugovk** [comment]
I can reproduce when using a token.

When the `user` object is created from `network.get_authenticated_user()`, it sets the `User.name` from `network.username`, which is blank.

Previously this didn't matter: `AuthenticatedUser.get_name()` was fetching the username via [`user.getInfo`](https://www.last.fm/api/show/user.getInfo), but that started failing with "Operation failed - Most likely the backend service failed. Please try again" so I removed it in https://github.com/pylast/pylast/commit/000993c3289405c9d5a50c896c47795a52075608.

But this does look like a Last.fm bug; calling [`user.getInfo`](https://www.last.fm/api/show/user.getInfo) should be possible without the username:

> **_user_** (Optional) : The user to fetch info for. Defaults to the authenticated user.

---

One workaround is to pass the username when creating the `network`.

```python
>>> network = pylast.LastFMNetwork(
    api_key=LASTFM_API_KEY,
    api_secret=LASTFM_API_SECRET,
    token=TOKEN_GENERATED_BY_LASTFM,
    username=username,
)
>>> user = network.get_authenticated_user()
...
```

Then that is stored in `network.username`, and them in `User.name`, meaning the call to [`user.getInfo`](https://www.last.fm/api/show/user.getInfo) now has a parameter.

---

Is this workaround any use for you?

And please could you report the "backend failed" problem to Last.fm at https://getsatisfaction.com/lastfm/categories/lastfm_api?

**Comment by themylogin** [comment]
I was able to workaround this by extracting authenticated user username from `auth.getSession` https://github.com/themylogin/last.fm.thelogin.ru/commit/28f294d9b1ad2dfd509c273989cf4bf5caddb316

**Comment by jacebrowning** [comment]
I was able to successfully integrate the workaround from @themylogin into my project:

```python
network = pylast.LastFMNetwork(
    api_key=settings.LASTFM_API_KEY,
    api_secret=settings.LASTFM_API_SECRET,
)
request = pylast._Request(network, "auth.getSession", {"token": token})
request.sign_it()
xml = request.execute()
username = xml.getElementsByTagName("name")[0].firstChild.data
print(username)
```

---

It looks like we might be able to patch `SessionKeyGenerator.get_web_auth_session_key` to also return the `username`: https://github.com/pylast/pylast/blob/718fba04b87d9d466e2f59d89c500348a12f3771/pylast/__init__.py#L1057

Then set `self.username` in the the `_Network` constructor if unset:
https://github.com/pylast/pylast/blob/718fba04b87d9d466e2f59d89c500348a12f3771/pylast/__init__.py#L207

What do think about that change @hugovk?

**Comment by hugovk** [comment]
Yes, a PR would be welcome, as long as there's no regressions.

Thank you!
