### ISSUE TITLE
How can I fetch more than one page?

### ISSUE THREAD

**Issue by homaralex** [pylast/pylast#283]
Is it possible to fetch more than the first page with API's like ```user.get_top_artists``` (see [https://www.last.fm/api/show/user.getTopArtists](https://www.last.fm/api/show/user.getTopArtists) ) ?

**Comment by hugovk** [comment]
Generally paging is taken care of automatically, just set the `limit` parameter to get how many results you need. There may be some functions that don't (yet) have the paging implemented, but we can probably add it if needed.

However, `user.get_top_artists` has it:

```python
>>> network = pylast.LastFMNetwork(api_key=API_KEY, api_secret=API_SECRET)
>>> network.get_user("rj")
pylast.User('rj', pylast.LastFMNetwork('b25b959554ed76058ac220b7b2e0a026', '425b55975eed76058ac220b7b4e8a054', '', '', ''))
>>> user = network.get_user("rj")
>>> tracks = user.get_top_tracks(limit=50)
>>> len(tracks)
50
>>> tracks = user.get_top_tracks(limit=100)
>>> len(tracks)
100
>>> tracks = user.get_top_tracks(limit=350)
>>> len(tracks)
350
```

**Comment by raean** [comment]
Hey! So, I've been using user_object.get_recent_tracks() to get the entire listening history of a user. I know that the Last.fm API actually allows for getting up to 200 songs per page. And some users have up to 30,000 songs. But the pylast version of the function only allows for 1000 and no paging. Does anyone have any suggestions? :)

**Comment by hugovk** [comment]
Try `user.get_recent_tracks(limit=None)`, I've used it to fetch 100k scrobbles. See also https://github.com/pylast/pylast/issues/296.

**Comment by raean** [comment]
I just saw someone else do that after some digging through the issues, it works! But for some users, it seems to run forever (since my machine is rather slow), so I'm thinking if I just want let's say 30,000 songs, I'll just run it on limit=1000 30 times, starting from the most recent date recorded.

**Comment by raean** [comment]
So, I've seemed to encounter another problem, haha. I've added my code at the bottom. It seems that no matter whether I set the `time_from` or `time_to` parameter as the most recently recorded date, it always starts from the very beginning. Is it because I'm using the same date format as the `user_object.get_recent_tracks()` returns?

```
username = sys.argv[1]
start = time.time()
try:
    i = 0
    last_recorded_time = ""
    while i < 3:
        user_object = last_fm_network.get_user(username)
        if last_recorded_time == "":
            history = user_object.get_recent_tracks(limit=1000, cacheable=True)
        else:
            history = user_object.get_recent_tracks(limit=1000, cacheable=True, time_to=last_recorded_time)
        for item in history:
            print(item[0].artist.get_name() + "," + item[0].title + "," + item[2]) # records the artist name, track name and date listening to.
            last_recorded_time = item[2]
        i = i + 1
except Exception as e:
    print(str(e))
```

**Comment by hugovk** [comment]
They're probably all Unix timestamps, but please can you open a new issue and I'll check it when I get the chance? In the meantime you could also check the source/docstrings/Last.fm API docs. Thank you!
