### ISSUE TITLE
get_recent_tracks(4) returns just one song:

### ISSUE THREAD

**Issue by nitanmarcel** [pylast/pylast#284]
### What did you do?

I'm trying to get the last 4 played songs

### What did you expect to happen?
The output should be:

Track1
Track2
Track3
Track4

### What actually happened?

But the output is:

Track1

### What versions of OS, Python and pylast are you using?
Python 3.6.5

```def get_recents(self, max_results):
        recents = self.user.get_recent_tracks(max_results)
        for song in recents:
            return str(song.track)
```

**Comment by hugovk** [comment]
The problem is your code returns immediately on the first track. 

See:

https://stackoverflow.com/a/53366468/724176
