### ISSUE TITLE
Is there any way to get an Artist's profile picture from just an Artist object?

### ISSUE THREAD

**Issue by Okyrrd** [pylast/pylast#304]
I thought Artist().get_cover_image() would have done this, but I am just getting blank stars.

**Comment by hugovk** [comment]
Thanks for the report.

Yes, that's the way to do it, but looks like a bug at the Last.fm side:

```python
Python 3.7.3 (default, Mar 27 2019, 09:23:15)
[Clang 10.0.1 (clang-1001.0.46.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pylast
>>> API_KEY = ...
>>> API_SECRET = ...
>>> network = pylast.LastFMNetwork(api_key=API_KEY, api_secret=API_SECRET)
>>> artist = network.get_artist("Radiohead")
>>> artist.get_cover_image()
'https://lastfm-img2.akamaized.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png'
```

https://lastfm-img2.akamaized.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png looks like 
![image](https://user-images.githubusercontent.com/1324225/57912079-1ab2e200-7892-11e9-90be-f29b12d21433.png)

Also reproducible via https://www.last.fm/api/show/artist.getInfo.

I've reported this to Last.fm:

* https://getsatisfaction.com/lastfm/topics/artist-getinfo-images-are-blank-stars?rfm=1&topic_submit=true

**Comment by hugovk** [comment]
Unfortunately Last.fm have announced this is against their terms of use and removed them from the API:

> We’ve made changes to our API in order to limit abuse and improve the service for everyone, in line with our [API Terms of Use](https://www.last.fm/api/tos). 
>
> While we allow API users to have access to a lot of data through the API, it has always been against our [API Terms of Use](https://www.last.fm/api/tos) for third parties to use audio, audiovisual, images or artwork. In some instances, some data may have been indirectly accessible through a small number of API calls, and so as part of the recent API clean-up, we have corrected that anomaly.
>
> If your application is affected, please refer to our [API Terms of Use](https://www.last.fm/api/tos) to ensure your compliance.

https://getsatisfaction.com/lastfm/topics/api-announcement-dac8oefw5vrxq

I suggest you use another API to fetch images, and you can find some examples in that thread.
