### ISSUE TITLE
Tag get_weekly_charts() results in WS error

### ISSUE THREAD

**Issue by vorkuta** [pylast/pylast#308]
### What did you do?

Tried to use .get_weekly_charts() on a tag

### What did you expect to happen?

to return the weekly chart for a given week (not included in example)

### What actually happened?
```
/usr/local/lib/python3.7/site-packages/pylast/__init__.py in _check_response_for_errors(self, response)
    982             status = e.getAttribute("code")
    983             details = e.firstChild.data.strip()
--> 984             raise WSError(self.network, status, details)
    985 
    986 

WSError: Invalid Method - No method with that name in this package
```
### What versions of OS, Python and pylast are you using?

OSX / Linux, Python 3.7

Please include **code** that reproduces the issue.

The [best reproductions](https://stackoverflow.com/help/mcve) are [self-contained scripts](https://ericlippert.com/2014/03/05/how-to-debug-small-programs/) with minimal dependencies.

```python
def get_tag( tag ):
	tag = network.get_tag(tag)
	return tag

tag = get_tag("rock")

tag.get_weekly_album_charts(from_date=, to_date=)
```

**Comment by hugovk** [comment]
`get_weekly_album_charts` is only available users, not tags: 

```python
>>> help(tag.get_weekly_album_charts)
Help on method get_weekly_album_charts in module pylast:

get_weekly_album_charts(from_date=None, to_date=None) method of pylast.Tag instance
    Returns the weekly album charts for the week starting from the
    from_date value to the to_date value.
    Only for User.
```

See also https://www.last.fm/api/

**Comment by timothydereuse** [comment]
I had the same problem, but with the tag.get_weekly_artist_charts() method, which does indicate that it's available for tags:

```python
help(tag.get_weekly_artist_charts)

Help on method get_weekly_artist_charts in module pylast:

get_weekly_artist_charts(from_date=None, to_date=None) method of pylast.Tag instance
    Returns the weekly artist charts for the week starting from the
    from_date value to the to_date value.
    Only for Tag or User.
```

This returns the same WSError. I'm confused because the tag.get_weekly_chart_list() method works fine, but I can't find anything in pylast or in the last.fm API where the timestamps returned by this method could actually be used to get tag-specific charts.

**Comment by hugovk** [comment]
Looks like Last.fm removed `tag.get_weekly_artist_charts` / `Tag.getWeeklyArtistChart` as part of their "re-imagining". It's no longer listed on the API page:

* https://www.last.fm/api/

It was removed from the docs between 13 and 14th January 2016:

* https://web.archive.org/web/20160113041418/http://www.last.fm/api
* https://web.archive.org/web/20160114204951/http://www.last.fm/api

There's also no test for `tag.get_weekly_artist_charts`. 

PR https://github.com/pylast/pylast/pull/311 will update the docstring.
