### ISSUE TITLE
Unable to get_recent_tracks using pylast due to "TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'"

### ISSUE THREAD

**Issue by pollystewart** [pylast/pylast#313]
### What did you do?
I am trying to get all of my played songs, so used the following:

```python
recent_tracks = user.get_recent_tracks(limit = None, cacheable=True)
```

### What did you expect to happen?
I expected this to get all the recent tracks. When I have used an integer as the limit value there is no issue:

```python
recent_tracks = user.get_recent_tracks(limit = 5, cacheable=True)
```

Within the pylast Git for the get_recent_tracks, it says:

```
Parameters:
        limit : If None, it will try to pull all the available data.
```

### What actually happened?
When using None rather than an integer, I got this error:

```
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
```

### What versions of OS, Python and pylast are you using?
Python 3.7.3
macOS Catalina, Versio 10.15
pylast = 3.2.0.dev0

```python
recent_tracks = user.get_recent_tracks(limit = None, cacheable=True)
```

**Comment by Stack-Attack** [comment]
It seems that this problem is back in newer release versions? I'm getting the same error when using:
`user.get_recent_tracks(time_from=date, limit=None)`

**Comment by Stack-Attack** [comment]
I've tracked the issue down to the changes around the limit and tracks now playing made in version 3.2.

#310 

It should be a simple fix of just checking for a None value before adding 1. @pollystewart can you re-open this?

**Comment by hugovk** [comment]
Thanks for tracking it down!

Please could you try out PR https://github.com/pylast/pylast/pull/320?
