### ISSUE TITLE
Album get_title() sometimes returns "Album not found" if properly_capitalized is set

### ISSUE THREAD

**Issue by spiritualized** [pylast/pylast#324]
Uncovered an corner case where calling get_title() on an album returns WSError: Album not found for a valid album, only if properly_capitalized is set to True.

Using latest pypi version, 3.2.1

This works:
```python
release = lastfm.get_album(":zoviet*france:", "Loh Land")
api_release.get_title()
```
This does not:
```python
release = lastfm.get_album(":zoviet*france:", "Loh Land")
api_release.get_title(properly_capitalized=True)
```

**Comment by hugovk** [comment]
Thanks for the report.

What is `lastfm.get_release`?

Is it the same as something like:

```python
import pylast

API_KEY = "TODO"
API_SECRET = "TODO"

network = pylast.LastFMNetwork(api_key=API_KEY, api_secret=API_SECRET)

album = network.get_album(":zoviet*france:", "Loh Land")
```

If so, I can reproduce it with that exammple:

```pycon
>>> album = network.get_album(":zoviet*france:", "Loh Land")
>>> album.get_title()
'Loh Land'
>>> album.get_title(properly_capitalized=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pylast/__init__.py", line 1539, in get_title
    self._request(self.ws_prefix + ".getInfo", True), "name"
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pylast/__init__.py", line 1118, in _request
    return _Request(self.network, method_name, params).execute(cacheable)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pylast/__init__.py", line 951, in execute
    response = self._download_response()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pylast/__init__.py", line 940, in _download_response
    self._check_response_for_errors(response_text)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pylast/__init__.py", line 970, in _check_response_for_errors
    raise WSError(self.network, status, details)
pylast.WSError: Album not found
```

But not with something like:

```pycon
>>> album = network.get_album("Nirvana", "Nevermind")
>>> album.get_title()
'Nevermind'
>>> album.get_title(properly_capitalized=True)
'Nevermind'
```

Perhaps it's related to the non-alpha characters in the name... Do you have other examples which don't work?

**Comment by spiritualized** [comment]
Thanks for the quick response. get_release was a wrapper for get_album, I've updated my original post accordingly.

On closer inspection, I think this is most likely yet another problem with the last.fm API itself. The album doesn't seem to have a full set of data associated with it, perhaps this is related.

This does not load:
http://ws.audioscrobbler.com/2.0/?method=album.getinfo&api_key=xxx&artist=:zoviet*france:&album=Loh%20Land&format=json
https://www.last.fm/music/:zoviet*france:/Loh+Land

However this does (same artist, so it's probably not a unicode issue):
http://ws.audioscrobbler.com/2.0/?method=album.getinfo&api_key=xxx&artist=:zoviet*france:&album=just%20an%20illusion&format=json
https://www.last.fm/music/:zoviet*france:/Just+An+Illusion

**Comment by hugovk** [comment]
`network.get_album` doesn't make any API calls, it just returns an `Album` object.

Similarly, `Album.get_title()` doesn't make any API calls, it just returns the title you gave when creating the object.

However, `Album.get_title(properly_capitalized=True)` does make an API call, to get info from Last.fm about the album, and return the canonical name Last.fm has for the album.

---

It's working for an artist with an asterisk:

```pycon
>>> album = network.get_album("B*Witched", "C'est la vie")
>>> album.get_title(properly_capitalized=True)
"C'est La Vie"
```

And with a colon:

```pycon
>>> album = network.get_album("D:Ream", "world")
>>> album.get_title(properly_capitalized=True)
'World'
```

But for some reason not for `:zoviet*france:`

---

However, if we get the artist, and then look up the top albums:

```pycon
>>> artist = network.get_artist(":zoviet*france:")
>>> artist.get_name(properly_capitalized=True)
':Zoviet*France:'
>>> albums = artist.get_top_albums(limit=20)
>>> albums[0]
TopItem(item=pylast.Album('Zoviet France', 'Decriminalisation Of Country Music', pylast.LastFMNetwork('TODO', 'TODO', '', '', '')), weight=39233)
>>> albums[11]
TopItem(item=pylast.Album('Zoviet France', 'Loh Land', pylast.LastFMNetwork('TODO', 'TODO', '', '', '')), weight=40425)
```

So for some reason, Last.fm have these under the name `Zoviet France`. Plugging that back in to the original query:

```
>>> album = network.get_album("Zoviet France", "Loh Land")
>>> album.get_title(properly_capitalized=True)
'Loh Land'
```

I'm not sure why it's doing this, there seems to be something strange on the Last.fm side.

For example, if you visit https://www.last.fm/music/:zoviet*france: in the browser, it redirects to https://www.last.fm/music/Zoviet+France 

![image](https://user-images.githubusercontent.com/1324225/76710736-9ed43100-6712-11ea-89bf-a9c17e77d074.png)

If you click to see the albums, and choose Loh Land, the link is https://www.last.fm/music/Zoviet+France/Loh+Land but it redirects to https://www.last.fm/music/:zoviet*france:/Loh+Land

![image](https://user-images.githubusercontent.com/1324225/76710786-e8bd1700-6712-11ea-9a26-daa3dadb7f56.png)

Some other albums are under `Zoviet France`, and others under `:zoviet*france:`

https://www.last.fm/music/Zoviet+France/Misfits,+Loony+Tunes+and+Squalid+Criminals
https://www.last.fm/music/Zoviet+France/Music+For+A+Spaghetti+Western
https://www.last.fm/music/:zoviet*france:/Shouting+at+the+Ground
https://www.last.fm/music/:zoviet*france:/Just+An+Illusion
https://www.last.fm/music/:zoviet*france:/The+Decriminalisation+of+Country+Music
https://www.last.fm/music/Zoviet+France/Gris
https://www.last.fm/music/Zoviet+France/Gesture+Signal+Threat
https://www.last.fm/music/:zoviet*france:/Norsch

So it appears that different albums appear under different canonical names, depending on what the band were using at the time (or how Last.fm has that data), and you need to use the right one?

**Comment by spiritualized** [comment]
Last.fm has support for aliasing, so common alternative names/misspellings will redirect to the correct entry. I believe this is what's happening here - https://www.last.fm/music/:zoviet*france: redirects to https://www.last.fm/music/Zoviet+France , however the same redirection isn't happening on the API. Unfortunately this is something which would have to be fixed on their end.

**Comment by hugovk** [comment]
https://getsatisfaction.com/lastfm/categories/lastfm_api would be the place to report it to Last.fm. Drop a link here if you do. Thanks!
