### ISSUE TITLE
Feature Request: Edit Scrobbles

### ISSUE THREAD

**Issue by ThomasThelen** [pylast/pylast#328]
### What did you do?
I looked through the tests and the main source file for anything related to editing scrobbles.

### What did you expect to happen?
I was _hoping_ that I'd see a method for editing scrobbles, but wasn't expecting anything since it's a subscription feature.

### What actually happened?
I didn't find any reference to editing scrobbles

### What versions are you using?
The master branch

I was curious if there is any interest in adding a feature for editing scrobbles.
Path: /user/<user-name>/library/edit

**Comment by hugovk** [comment]
Unfortunately there's no API for it at https://www.last.fm/api/

You could request it at https://getsatisfaction.com/lastfm, but I wouldn't be too hopeful.

**Comment by ThomasThelen** [comment]
Ah makes sense. I was originally looking to make a tool that lets people search their scrobbles for bogus recordings (ie tracks that have "Official Music Video, etc in their title). It looks like it would have to be a nasty web extension without an official API endpoint...

Thank you for the work with this API client, feel free to close this issue :)

**Comment by hugovk** [comment]
You're welcome!
