### ISSUE TITLE
get_now_playing does not contain album and coverart

### ISSUE THREAD

**Issue by vervaekejonathan** [pylast/pylast#329]
Hi -- Great library!

Got a little request for the `get_now_playing` function.
Since only the artist and the title are stored, the album information gets lost.

If you want to display the cover for the currently playing track, most of the time it's wrong because you have to 'search' for the album based on the artist's name and the track's name. 

Since the last.fm api already has this information inside the `User.getRecentTracks` call (album name and current coverart), it would be great if this would be returned by the `get_now_playing` function!

**Comment by hugovk** [comment]
Good idea, this could be done similar to https://github.com/pylast/pylast/pull/307 for `user.get_top_albums`.
