### ISSUE TITLE
pylast fails import when using Auto Py To Exe

### ISSUE THREAD

**Issue by bembidiona** [pylast/pylast#339]
### What did you do?
I'm trying to build an exe of my finished application, that has the scrobbling feature thanks to your library.
I'm using auto-py-to-exe 2.7.6 for this.

### What did you expect to happen?
Being able to freeze my script generating a .exe using auto-py-to-exe or pyInstaller
Every other external libraries imported by my main script (more than 8) are included in the final exe. But for some reason the pylast library is the only one not bundled when compiling the exe.

### What actually happened?
When runing the generated .exe, the application crash leaving this error:
```
pkg_resources.DistributionNotFound: The 'pylast' distribution was not found and is required by the application
```

### What versions are you using?
* OS: Windows 10 
* Python:  Python 3.8.2
* pylast: 3.3.0

### Example code
Even a simple script like this, when compiled by auto-py-to-exe, fails to import the pylast library. And when running the generated .exe the app crash with the above mentionated error.
```python
import pylast
print("DONE!")
```

**Comment by hugovk** [comment]
I'm not familiar with auto-py-to-exe, and can't think of anything in pylast that is unusual for a Python package. 

This might be a question for auto-py-to-exe.

I see at https://github.com/brentvollebregt/auto-py-to-exe says Python 3.8 is not supported, see https://github.com/pyinstaller/pyinstaller/issues/4311. 

Do you get the same thing with 3.7?

https://github.com/brentvollebregt/auto-py-to-exe/issues/71 also has a `pkg_resources.DistributionNotFound`. Do any of the suggestions in https://github.com/brentvollebregt/auto-py-to-exe/issues/71#issuecomment-533736044 help?

> Did you read my post on [Issues When Using auto-py-to-exe](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe/)? This is linked at the bottom of the UI after every build and in the README of this repository; I highly recommend you give it a read.
> 
> In the post I discuss the error of [modules not being found](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe/#modulenotfounderror-no-module-named-x-importerror-no-module-named-x). This is very similar to your issue here so you could try to add `scipy` as a hidden import.

There's also links to similar issues at pyinstaller that are worth checking out.

**Comment by bembidiona** [comment]
Thanks a lot for your response! It definitely put me in the right track and finally managed to make it work.
I was able to do it using just **PyInstaller**.  And still using Python 3.8

I needed to create this extra file in a hooks directory (at the same level that the main script):
#### myprogram/hooks/hook-pylast.py
```
from PyInstaller.utils.hooks import copy_metadata
datas = copy_metadata('pylast')
```
and then in the spec file (created the first time you run pyinstaller against your main_script_of_my_program.py), add this folder path to the `hookspath` argument in the Analysis part:
#### myprogram/main_script_of_my_program.spec
```
#more stuff at top

a = Analysis(['bandonautica.py'],
             pathex=['C:\\myprogram],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=["hooks"], # <---------------- ADD PATH TO HOOKS FOLDER HERE!
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)

#more stuff at bottom
```

**Comment by hugovk** [comment]
Good to hear, and thank you for posting an update of what worked, it might help someone else!
