### ISSUE TITLE
get_now_playing() returns None every time with every account

### ISSUE THREAD

**Issue by flfy** [pylast/pylast#351]
### What did you do?
Ran User.get_now_playing()

### What did you expect to happen?
Return the now playing Track object

### What actually happened?
Returned None on every try

### What versions are you using?

* OS: ubuntu
* Python: 3.8.5
* pylast: 3.2.1

Please include **code** that reproduces the issue.

The [best reproductions](https://stackoverflow.com/help/minimal-reproducible-example) are [self-contained scripts](https://ericlippert.com/2014/03/05/how-to-debug-small-programs/) with minimal dependencies.

```python
import pylast
fm = pylast.LastFMNetwork(api_key=redacted, api_secret=redacted)
user = fm.get_user("[redacted]")
user.get_now_playing()
```

**EDIT**
I've updated to 4.0.0 and the issue persists.

**Comment by hugovk** [comment]
Does it show if the user has a now playing track on their profile?

For example:

https://www.last.fm/user/bbcradio1

![image](https://user-images.githubusercontent.com/1324225/97713732-e56f7380-1ac8-11eb-99a2-36104239ed78.png)

And it works:

```pycon
>>> import pylast
>>> fm = pylast.LastFMNetwork(api_key=API_KEY, api_secret=API_SECRET)
>>> user = fm.get_user("bbcradio1")
>>> print(user.get_now_playing())
Martin Solveig & Roy Woods - Juliet & Romeo
>>>
```

**Comment by flfy** [comment]
I have solved that issue - so disregard, sorry.

Now that I've got it working - there's no album info attached, just a title and an artist to the Track object.

**Comment by hugovk** [comment]
Please open a new issue if this is still needed.

**Comment by lap-does-things** [comment]
I've figured out what causes this, so here goes for the future generations :
In my case, the error was caused by not having anything playing at the moment of launching the code, I fixed it as such:
`try : 
    # fancy code here
except Exception as e:
    print(e)
    pass`
