### ISSUE TITLE
Get Top Tracks is only getting 1 track

### ISSUE THREAD

**Issue by djotaku** [pylast/pylast#354]
### What did you do?

Use `user.get_top_tracks(period='overall')`

I tested both with my username (djotaku) and the API's default username (rj). Both only returned one track. When I go to the API website I get a all my tracks.

See lines 39 and 49 at https://github.com/djotaku/lastfmeoystats/blob/040eb6b3c92415d810cd305dece1c5b2f2818cdb/lastfmeoystats/main.py#L32-L49

```python
def get_annual_data(user):
    """Get annual data from last.fm.
    :param user: A pylast user object
    :returns: A tuple with the top artists, albums, and tracks of the last 12 months.
    """
    return user.get_top_artists(period='12month'), user.get_top_albums(period='12month'),\
           user.get_top_tracks(period='12month')  # line 39


def get_all_time_data(user):
    """Get overall data from last.fm.
        :param user: A pylast user object
        :returns: A tuple with the top artists, albums, and tracks for the entire user history.
        """
    return user.get_top_artists(period='overall'), user.get_top_albums(period='overall'), \
           user.get_top_tracks(period='overall')  # line 49
```

### What did you expect to happen?

To get up to 50 top tracks

### What actually happened?

Got just 1 top track

### What versions are you using?

* OS: Linux
* Python: 3.8
* pylast: 4.0.0

Please include **code** that reproduces the issue.

see https://github.com/djotaku/lastfmeoystats/blob/c0d01e76cd285bf9811a22b84f41fa6a9c385dd8/lastfmeoystats/main.py

**Comment by hugovk** [comment]
Thanks for the report, please could you test PR https://github.com/pylast/pylast/pull/355?

What happened, #243 (released in 2.1.0) set the default  for `limit` to 1 instead of the Last.fm default (50 for the APIs I checked). Instead, #355 now defaults to 50.

You can set a different `limit` if you prefer.

---

Here's a shorter repro:

```python
import pylast

API_KEY = TODO
API_SECRET = TODO

print(pylast.__version__)

network = pylast.LastFMNetwork(api_key=API_KEY, api_secret=API_SECRET)

user = network.get_user("rj")

tracks = user.get_top_tracks(period="12month")
print(len(tracks))
assert len(tracks) == 50
```

**Comment by djotaku** [comment]
I assume the branch to test from is fix-default-limit? If so....

Yes, I can confirm that it works.

**Comment by hugovk** [comment]
Yep, that's the one. Thanks for testing! I'll merge and get a release out in the next week or so.
