### ISSUE TITLE
Migrate to HTTPX library for making HTTP requests

### ISSUE THREAD

**Issue by djmattyg007** [pylast/pylast#361]
I think it would be a great idea for this project to migrate to using a `requests` `Session` object for all HTTP requests. This would have several benefits, including but not limited to the following:

- Hopefully start the process of resolving #105, as `requests` has very well supported mocking mechanisms
- Support more flexible and powerful proxy configuration
- Allow customisation of supplied HTTP headers, including but not limited to the user agent

My primary use case for this switch is a cleaner integration into the music server software Mopidy. Ideally, Mopidy extensions should transparently make use of the HTTP proxy configuration set up by the end user. They're also supposed to represent themselves as a Mopidy extension to HTTP servers. By switching to `requests`, the Mopidy Scrobbler extension would be able to achieve these things.

I suspect this kind of update would probably result in some breaking changes, and would therefore likely form the backbone of a new major version. Would you be willing to accept a pull request that makes the switch to `requests`?

**Comment by hugovk** [comment]
If something like this is done, my preference would be for [HTTPX](https://github.com/encode/httpx) as it has a much more promising future than Requests. How does that sound?

**Comment by djmattyg007** [comment]
Interesting. I hadn't heard of HTTPX until now. I had a quick read through the docs and it seems fine.

While I'm perfectly happy to work with HTTPX on this project, I am curious about your concerns with requests. I suppose a big concern for them is that it will be extraordinarily difficult to improve and change the API (such as for async support)  since it's achieved such widespread usage.

**Comment by hugovk** [comment]
Yes, that's part of it: HTTPX is more likely to have longer term development, especially for new stuff. Requests also went through a patch of uncertain maintenance, and whilst it's looking more settled now, HTTPX feels a safer bet.

Thanks!

**Comment by djmattyg007** [comment]
I just took a brief dive into the requests issue tracker, and yeah, it seems like they're a long way away from ever implementing async support. HTTPX seems like the way to go for a brand new task.

If you're happy for me to start working on a migration to HTTPX, I'll see what I can do!

**Comment by hugovk** [comment]
That would be great, thank you!

**Comment by hugovk** [comment]
Hi! We'll be dropping support for Python 3.6 soon because it'll be EOL (see https://github.com/pylast/pylast/pull/378) and that warrants a major version bump.

Which would also be a good time for switching to HTTPX, because there's scope for breaking changes; if nothing else, some of the underlying networking exceptions will change.

I've created https://github.com/pylast/pylast/pull/379 to migrate to HTTPX and so far it's working fine for me.

I tried to keep the changes fairly minimal, we can make more improvements in the future.

Please could you have a look?

One path I can't test though is a proxy via `network.enable_proxy()`. Is this something you can test?

**Comment by djmattyg007** [comment]
I've added some comments to the PR :) Thank you for tackling this, I'm sorry I wasn't able to get to it myself.
