### ISSUE TITLE
Pylast.Track.get_correction() Error

### ISSUE THREAD

**Issue by yajrendrag** [pylast/pylast#364]
### What did you do?
returned a `Pylast.Track` object by doing a `network.get_track("artist", "title")`
e.g., `lfmTrack = network.get_track("artist", "title")`
did a `get_correction()` on the returned object,
e.g., `correctedTrackName = lfmTrack.get_correction()`

### What did you expect to happen?
i expected the title to be corrected

### What actually happened?
the title was set to the artist - and not corrected
BUT ONLY if the title string ends with a space - e.g., "Song Title "

Only discovered this because one of the sources i use returns a title with a space at the end of the name, which is easy enough to workaround, but should be fixed IMHO.

### What versions are you using?

* OS:  ubuntu 20.04
* Python:  3.8, 3.8.5 - see same behavior on both versions
* pylast:  4.1.0

Please include **code** that reproduces the issue.

The [best reproductions](https://stackoverflow.com/help/minimal-reproducible-example)
are
[self-contained scripts](https://ericlippert.com/2014/03/05/how-to-debug-small-programs/)
with minimal dependencies.

```python
artist = "REO Speedwagon"
title  = "Roll With The Changes "
lfmTrack = network.get_track(artist, title)
correctedTrackName = lfmTrack.get_correction()
```
I picked this artist/title as i was listening to it while i documented this issue - but any artist/title combo with a space at the end of the title produces the same result.

**Comment by hugovk** [comment]
Does the same thing happen when calling the Last.fm API directly?

https://www.last.fm/api/show/track.getCorrection

**Comment by yajrendrag** [comment]
hmmm... good point - it doesn't return correctly either.  the return is truncated showing only the artist name, & doesn't return a track name at all.  Guess i should open the issue there instead..

**Comment by hugovk** [comment]
Yes, please do and add a link here. Thanks!

**Comment by yajrendrag** [comment]
opened an issue on Last.fm's api support forum:
https://support.last.fm/t/track-getcorrection-error/40818
