### ISSUE TITLE
Can't get unlimited user top_tracks

### ISSUE THREAD

**Issue by ChandlerSwift** [pylast/pylast#366]
### What did you do?
```python
tracks = network.get_user("chandlerswift").get_top_tracks(limit=None)

for i, track in enumerate(tracks):
    print(f"{i}: {track}")
```
### What did you expect to happen?
Print all my top tracks
### What actually happened?
Prints the first 50 tracks:
```
python main.py
0: TopItem(item=pylast.Track('Oscar Peterson Trio', 'You Look Good To Me', pylast.LastFMNetwork('cb53840d659b386c711c6b38c25b3067', 'f36a5aad3d870251a74c0b9ac25741fc', '', '', '')), weight=690)
1: TopItem(item=pylast.Track('Ben Paterson', 'Lucky Southern', pylast.LastFMNetwork('cb53840d659b386c711c6b38c25b3067', 'f36a5aad3d870251a74c0b9ac25741fc', '', '', '')), weight=649)
[...]
48: TopItem(item=pylast.Track('Cyrille Aimee', 'Paper Moon', pylast.LastFMNetwork('cb53840d659b386c711c6b38c25b3067', 'f36a5aad3d870251a74c0b9ac25741fc', '', '', '')), weight=83)
49: TopItem(item=pylast.Track('Greg Jasperse', 'Dandaya', pylast.LastFMNetwork('cb53840d659b386c711c6b38c25b3067', 'f36a5aad3d870251a74c0b9ac25741fc', '', '', '')), weight=83)
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f26cd318250>
```
### What versions are you using?
Arch Linux, Python 3.9, Pylast 4.2.0
```
(.venv) chandler@xenon ~/projects/spotify-listen-percentage % uname -a
Linux xenon 5.11.16-arch1-1 #1 SMP PREEMPT Wed, 21 Apr 2021 17:22:13 +0000 x86_64 GNU/Linux
(.venv) chandler@xenon ~/projects/spotify-listen-percentage % python --version
Python 3.9.4
(.venv) chandler@xenon ~/projects/spotify-listen-percentage % pip freeze
aiohttp==3.7.4.post0
async-timeout==3.0.1
attrs==20.3.0
backoff==1.10.0
chardet==4.0.0
idna==3.1
multidict==5.1.0
pylast==4.2.0
spotify==0.10.2
typing-extensions==3.7.4.3
yarl==1.6.3
(.venv) chandler@xenon ~/projects/spotify-listen-percentage %
```
Please include **code** that reproduces the issue.

```python
#!/usr/bin/env python3

import pylast
import os

network = pylast.LastFMNetwork(
    api_key=os.getenv("LASTFM_API_KEY"),
    api_secret=os.getenv("API_SECRET")
)

tracks = network.get_user("chandlerswift").get_top_tracks(limit=None)

for i, track in enumerate(tracks):
    print(f"{i}: {track}")
```

I think the issue here is that when I call `get_top_tracks` with `limit=None`, https://github.com/pylast/pylast/blob/4.2.0/src/pylast/__init__.py#L2534 doesn't set the limit (since `None` evaluates to `false`), and then https://github.com/pylast/pylast/blob/4.2.0/src/pylast/__init__.py#L1161 sets it to 50. I could override it to, say, 999999 to (almost certainly) get all of my songs, but being able to say "no limit" would be nice, since the docs specifically say it should be supported. 

I think either
```diff
diff --git a/src/pylast/__init__.py b/src/pylast/__init__.py
index 1341de0..44f4023 100644
--- a/src/pylast/__init__.py
+++ b/src/pylast/__init__.py
@@ -1158,7 +1158,7 @@ class _BaseObject:
         """Returns a list of the most played thing_types by this thing."""
 
         def _stream_get_things():
-            limit = params.get("limit", 50)
+            limit = params.get("limit", None)
             nodes = _collect_nodes(
                 limit,
                 self,
```
or
```diff
diff --git a/src/pylast/__init__.py b/src/pylast/__init__.py
index 1341de0..40f7468 100644
--- a/src/pylast/__init__.py
+++ b/src/pylast/__init__.py
@@ -2531,8 +2531,7 @@ class User(_Chartable):
 
         params = self._get_params()
         params["period"] = period
-        if limit:
-            params["limit"] = limit
+        params["limit"] = limit
 
         return self._get_things("getTopTracks", Track, params, cacheable, stream=stream)
```
would fix the issue. I think the second is cleaner, so I'm going to open a PR for that, but I'd be happy to do the second if that makes more sense in the context of where this tends to be used.

**Comment by hugovk** [comment]
> since the docs specifically say it should be supported.

Please could you point me to this? I couldn't find it in pylast, and Last.fm says [`user.getTopTracks`](https://www.last.fm/api/show/user.getTopTracks):

> **limit** (Optional) : The number of results to fetch per page. Defaults to 50.
> **page** (Optional) : The page number to fetch. Defaults to first page.

Which would default to a single page of 50.

Thanks!

**Comment by ChandlerSwift** [comment]
Ah, my bad. I'd been looking at the docs for different functions and it looks like I've gotten them mixed up. I think I was specifically thinking of `get_recent_tracks` (https://github.com/pylast/pylast/blob/master/src/pylast/__init__.py#L2349):
> limit : If None, it will try to pull all the available data.

There are a handful of other functions with similar phrasings, it seems: 

https://github.com/pylast/pylast/blob/master/src/pylast/__init__.py#L1983:

https://github.com/pylast/pylast/blob/master/src/pylast/__init__.py#L2277

> if limit==None it will return all (may take a while)`

The impression that I have from skimming the code is that there are a handful that explicitly say "`limit=None` will let you get all results; there are some more for which that works (and often is the default) but isn't mentioned in the docs one way or another, and that there are more yet where a relatively minor change like this one enables paging, since it looks like there's a really nicely written `_get_things` function that enables streaming items. However, as I've only been using the `top_tracks` function, that's the only one I can speak on with any confidence.
