### ISSUE TITLE
Malformed response from fetching recent tracks

### ISSUE THREAD

**Issue by adriancaruana** [pylast/pylast#381]
### What did you do?

Tried to fetch recent tracks.

### What did you expect to happen?

Recent tracks to be fetched.

### What actually happened?

`_Request` throws `MalformedResponseError` when parsing the XML.

### What versions are you using?

* OS: Ubuntu
* Python: 3.8.8
* pylast: 4.4.0

Please include **code** that reproduces the issue.

The [best reproductions](https://stackoverflow.com/help/minimal-reproducible-example)
are
[self-contained scripts](https://ericlippert.com/2014/03/05/how-to-debug-small-programs/)
with minimal dependencies.

```python
import pylast
from pylast import _Request

api_key = ""
api_secret = ""

username = "o_ded"

network = pylast.LastFMNetwork(
    api_key=api_key,
    api_secret=api_secret,
    username=username,
    password_hash=None,
)

user = pylast.User(username, network)

method_name = user.ws_prefix + ".getRecentTracks"
page=1820
params = dict(
    limit=200,  # limit (Optional) : The number of results to fetch per page. Defaults to 50. Maximum is 200.
    user=username,  # user (Required) : The last.fm username to fetch the recent tracks of.
    page=page,  # page (Optional) : The page number to fetch. Defaults to first page.
    extended=1,  # extended (0|1) (Optional) : Includes extended data in each artist, and whether or not the user has loved each track
    api_key=api_key,  # api_key (Required) : A Last.fm API key.
)

_Request(network, method_name, params).execute()
```

### Here is the traceback

```
---------------------------------------------------------------------------
ExpatError                                Traceback (most recent call last)
<ipython-input-6-cd419f3b0117> in <module>
     29 )
     30 
---> 31 _Request(network, method_name, params).execute()

~/.local/lib/python3.8/site-packages/pylast/__init__.py in execute(self, cacheable)
    983             response = self._download_response()
    984 
--> 985         return minidom.parseString(_string(response).replace("opensearch:", ""))
    986 
    987     def _check_response_for_errors(self, response):

/opt/conda/lib/python3.8/xml/dom/minidom.py in parseString(string, parser)
   1967     if parser is None:
   1968         from xml.dom import expatbuilder
-> 1969         return expatbuilder.parseString(string)
   1970     else:
   1971         from xml.dom import pulldom

/opt/conda/lib/python3.8/xml/dom/expatbuilder.py in parseString(string, namespaces)
    923     else:
    924         builder = ExpatBuilder()
--> 925     return builder.parseString(string)
    926 
    927 

/opt/conda/lib/python3.8/xml/dom/expatbuilder.py in parseString(self, string)
    221         parser = self.getParser()
    222         try:
--> 223             parser.Parse(string, True)
    224             self._setup_subset(string)
    225         except ParseEscape:

ExpatError: not well-formed (invalid token): line 4131, column 28
```

### Here is the suspicious XML:
```xml
    <track>
      <artist>
        <name>יצחק קלפטר</name>
        <mbid></mbid>
        <url>https://www.last.fm/music/%D7%99%D7%A6%D7%97%D7%A7+%D7%A7%D7%9C%D7%A4%D7%98%D7%A8</url>
        <image size="small">https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png</image>
        <image size="medium">https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png</image>
        <image size="large">https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png</image>
        <image size="extralarge">https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png</image>
      </artist>
      <loved>0</loved>
      <name>ריגושים</name>
      <streamable>0</streamable>
      <mbid></mbid>
      <album mbid="">הרחובותሑ</album>
      <url>https://www.last.fm/music/%D7%99%D7%A6%D7%97%D7%A7+%D7%A7%D7%9C%D7%A4%D7%98%D7%A8/_/%D7%A8%D7%99%D7%92%D7%95%D7%A9%D7%99%D7%9D</url>
      <image size="small">https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png</image>
      <image size="medium">https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png</image>
      <image size="large">https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png</image>
      <image size="extralarge">https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png</image>
      <date uts="1284418858">13 Sep 2010, 23:00</date>
    </track>
```

**Comment by hugovk** [comment]
As the `page` is changing as more tracks are scrobbled (currently `page = 1821` is required), here's another way:

```python
...
user = pylast.User(username, network)

tracks = user.get_recent_tracks(time_from=1284418850, time_to=1284418859)
```

There's something up with the parsing, possibly because the text direction changes at an unexpected place. If we add something like this to `_check_response_for_errors`:

```python
        lines = response.splitlines()
        import unicodedata
        for c in lines[20]:
            print(c, unicodedata.bidirectional(c))
```

It'll print out each character and the detected text direction:

```
  WS
  WS
  WS
  WS
  WS
  WS
< ON
a L
l L
b L
u L
m L
  WS
m L
b L
i L
d L
= ON
" ON
" ON
> ON
ה R
ר R
ח R
ו R
ב R
ו R
ת R
 BN
ሑ L
< ON
/ CS
a L
l L
b L
u L
m L
> ON
```

Codes: https://www.unicode.org/reports/tr9/tr9-18.html#Bidirectional_Character_Types

So after the initial XML we have 7 Hebrew characters R=right-to-left, then a BN=boundary neutral, but then another Hebrew character "ሑ" L=left-to-right, then the remaining XML.

Why is ሑ LTR? What is that BN char? Printing out the Unicode code points:

```diff
        for c in line:
-            print(c,unicodedata.bidirectional(c))
+            print(c, ord(c), unicodedata.bidirectional(c))
```

```
  32 WS
  32 WS
  32 WS
  32 WS
  32 WS
  32 WS
< 60 ON
a 97 L
l 108 L
b 98 L
u 117 L
m 109 L
  32 WS
m 109 L
b 98 L
i 105 L
d 100 L
= 61 ON
" 34 ON
" 34 ON
> 62 ON
ה 1492 R
ר 1512 R
ח 1495 R
ו 1493 R
ב 1489 R
ו 1493 R
ת 1514 R
 5 BN
ሑ 4625 L
< 60 ON
/ 47 CS
a 97 L
l 108 L
b 98 L
u 117 L
m 109 L
> 62 ON
```

The BN has code point 5 = ENQ Enquiry character

https://en.wikipedia.org/wiki/List_of_Unicode_characters#Control_codes

> In computer communications, enquiry is a transmission-control character that requests a response from the receiving station[1] with which a connection has been set up.[2] It represents a signal intended to trigger a response at the receiving end, to see whether it is still present. The response, an answer-back code to the terminal that transmitted the WRU (who are you) signal, may include station identification, the type of equipment in service, and the status of the remote station.

https://en.wikipedia.org/wiki/Enquiry_character

I'm not really sure what this is doing here!

**Comment by adriancaruana** [comment]
Thanks for the additions to the reproduction code. 

It seems that the Element Tree library intentionally forgoes some data quality checks in the name of performance.
https://stackoverflow.com/a/62099920

The API responses could potentially contain arbitrary user input in song/album/artist name fields, so I'd say this needs to be handled somehow. Considering that this is an exceedingly uncommon issue (perhaps this is the first time you've encountered it), I'd say the best solution, for the time being, is to try and catch the error, and then perform a `re.sub()` of some description.

**Comment by hugovk** [comment]
Sounds reasonable, how does https://github.com/pylast/pylast/pull/382 look?

**Comment by adriancaruana** [comment]
Looks good to me :) 
I'll close this once the PR is merged.
