### ISSUE TITLE
Oauth authentication

### ISSUE THREAD

**Issue by adammpkins** [pylast/pylast#417]
### What did you do?
I want to use this library in an application which will authenticate the user, then allow them to do scrobbling based on that authentication. Your examples all seem to involve hardcoding (or potentially storing in a database) a user's password. 

### What did you expect to happen?
OAuth was made for this use case, and I can't seem to find any support for oauthing users in this library

### What actually happened?
Right now I seem to be stuck hardcoding an individual user or asking the user for their password.

Am I missing something in the docs, or is Oauth not implemented in this library?

**Comment by hugovk** [comment]
Do you mean web auth? You can do it like https://github.com/pylast/pylast/issues/407#issuecomment-1164053561 / https://github.com/pylast/pylast/pull/409

**Comment by ndm13** [comment]
I was also unaware that this was possible. The referenced issue mentioned updating the docs, is there a timeline for this?

**Comment by adammpkins** [comment]
> I was also unaware that this was possible. The referenced issue mentioned updating the docs, is there a timeline for this?

Yes. I was able to use this successfully. It needs to be documented. @ndm13 You could submit a PR. I may if you don't.

**Comment by ndm13** [comment]
This PR just includes the code from #407.  Feel free to clean up or streamline.
