### ISSUE TITLE
Is it possible to remove scrobbles

### ISSUE THREAD

**Issue by bonelifer** [pylast/pylast#440]
### What did you do?
I use Pandora on my android phone. The scrobbler I use supports Pandora. Unfortunately a lot of Curated Messages end up scrobbled. 

Is it possible to do this with pylast.

**Comment by hugovk** [comment]
It used to be possible, but Last.fm "reimagined" their website and the API to remove scrobbles went away (see https://github.com/pylast/pylast/issues/199).

I've recently used a Chrome extension to delete scrobbles, maybe this is helpful:

https://chromewebstore.google.com/detail/lastfm-unscrobbler/pjlmjmkpaklofeinjkhhdcggbgjhahek

**Comment by bonelifer** [comment]
Thanks for the answer. Unfortunately sometimes when people re-imagine, its usually the ones without imaginations. :(
