### ISSUE TITLE
MusicBrainz and Spotify track IDs

### ISSUE THREAD

**Issue by svshepherd** [pylast/pylast#452]
This is less an issue than a feature request; please lmk if this is not the best way to suggest. 

I understand there's an endpoint that gives us the musicbrainz id of a track (sometimes) for each track played. I suspect this is mediated by a last.fm request to musicbrainz to get a response; it's thus slow. 

But if we're going to the trouble of getting an mbid through this path, it sure would be nice to also get a spotify id for the track at the same time. 

Is this something we could consider? If it's beyond the scope of the project, no problem. If it'd be a bit of a lift but something folks might be interested in, I'm curious how we could implement.

**Comment by hugovk** [comment]
We can get the MBID using pylast calls like `get_mbid`.

This calls Last.fm API `getInfo` endpoints like https://www.last.fm/api/show/track.getInfo which have fields like `<mbid>61bf0388-b8a9-48f4-81d1-7eb02706dfb0</mbid>`, but don't have any Spotify info.

pylast only uses Last.fm APIs, and doesn't use any MusicBrainz APIs.

It's out of scope to add calls to the Spotify API to this project. Perhaps you can use https://spotipy.readthedocs.io.

**Comment by svshepherd** [comment]
Thanks -- I suspect last.fm is using the musicbrainz API under the hood, and I've heard a claim that the musicbrainz API can provide a spotify ID.  But it sounds like this is indeed out-of-scope.  Thanks for thinking about it and sharing the information!
