### ISSUE TITLE
Broken Python 3.2 combatibility

### ISSUE THREAD

**Issue by tubersan** [pylast/pylast#91]
This commit broke compatibility to python3: https://github.com/hugovk/pylast/commit/c6c8d45635a4d62b4f53d23da2b3ba138a6609e7
It can simply be fixed for python3 by removing the u before the strings in [lines 120-122](https://github.com/hugovk/pylast/blob/master/pylast.py#L120-L122).

**Comment by hugovk** [comment]
In case anyone still needs Python 3.2 support, the previous version [0.5.11 is on PyPI](https://pypi.python.org/pypi?:action=display&name=pylast&version=0.5.11), and can be installed like:
```bash
pip install pylast==0.5.11
```

**Comment by hugovk** [comment]
Python 3.2 was only supported until February 2016, so closing this.

https://en.wikipedia.org/wiki/CPython#Version_history
